language: java
env:
 global:
  - SONATYPE_USERNAME=mihxil
  - secure: Xe9cNQJI3b8zfcQxTCXOKefowBCQQ30k/bs9LYk5CwrUuU7Y2Kcs7+NZpWLmnNHblfPT9QBUwyrL8sy/Vw4toWNQMXcktSJllzKVSdeo7bo7bg83sGKXahx1HERE8poTdSmp58uUSTM/YgYARftOBA/puCl/2xBNMNOQtLGBPYA=

jdk:
- oraclejdk8

sudo: false

script: mvn clean test install

after_success:
- mvn deploy --settings travis-settings.xml -DskipTests=true -B
