language: java
env:
  global:
  - SONATYPE_USERNAME=vpro
  - secure: JGi3VM0XMxgp+tdUwgsr2UHbGVEm2rFCFDwctYk2xpt/e5QFbFhFjbcx+KLd4JGSFA3TKUAOkhYu3My+lYM2x0pDCYZWgYp5TXOysRiiQma6hgzF23QAgta/TwcEhsOw3DrQazi0D8RkUAu1BC5CFx3MwkARUIQU6gDWHSrEAfQ=
jdk:
- oraclejdk8
sudo: false
script: mvn clean test install
after_success:
- mvn -Pdeploy deploy --settings .travis-settings.xml -DskipTests=true -Dgpg.skip=true  -B
- bash <(curl -s https://codecov.io/bash)
